// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrackerEntry(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddTrackerEntry'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddTrackerEntryUpdate(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddTrackerEntryUpdate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeleteDrink(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteDrink'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAlcoholCategories() {
  return window['go']['main']['App']['GetAlcoholCategories']();
}

export function GetDaysSinceLastDrink() {
  return window['go']['main']['App']['GetDaysSinceLastDrink']();
}

export function GetDrinkCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDrinkCount'](arg1, arg2, arg3);
}

export function GetDrinkTagColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDrinkTagColor'](arg1, arg2, arg3);
}

export function GetDrinks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDrinks'](arg1, arg2, arg3);
}

export function GetEntriesByDate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetEntriesByDate'](arg1, arg2, arg3, arg4);
}

export function GetEntriesOnDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEntriesOnDate'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function ValidateFormDate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateFormDate'](arg1, arg2, arg3);
}
